### ISSUE TITLE
[BUG]: Without ingress, error in the frontend

### ISSUE THREAD

**Issue by nlamirault** [keephq/helm-charts#88]
### Description of the bug

If i try to use Keep without ingress configuration, and with port-forward, i've got this error 

```
Application error: a client-side exception has occurred (see the browser console for more information).
```

Using this configuration, https://docs.keephq.dev/deployment/kubernetes/installation#without-ingress-not-recommended

### Steps To Reproduce

https://docs.keephq.dev/deployment/kubernetes/installation#without-ingress-not-recommended

### Additional Information

in the browser console:

```
ingest.keephq.dev/static/web-vitals.js?v=1.186.1:1 

       Failed to load resource: net::ERR_BLOCKED_BY_CLIENTUnderstand this errorAI
pusher.js:3742 WebSocket connection to 'ws://localhost/websocket/app/keepappkey?protocol=7&client=js&version=8.3.0&flash=false' failed: 
createWebSocket @ pusher.js:3742Understand this errorAI
ingest.keephq.dev/static/web-vitals.js?v=1.186.1:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENTUnderstand this errorAI
app-index.tsx:25 TypeError: Cannot read properties of undefined (reading 'map')
    at page.client.tsx:53:66
    at aW (react-dom.production.min.js:212:342)
    at oe (react-dom.production.min.js:240:225)
    at ol (react-dom.production.min.js:243:85)
    at or (react-dom.production.min.js:242:69)
    at ol (react-dom.production.min.js:244:62)
    at or (react-dom.production.min.js:242:69)
    at ol (react-dom.production.min.js:244:62)
    at or (react-dom.production.min.js:242:69)
    at ol (react-dom.production.min.js:243:50)
window.console.error @ app-index.tsx:25Understand this errorAI
app-index.tsx:25 TypeError: y.map is not a function
    at E (AlertsLinks.tsx:122:55)
    at rE (react-dom.production.min.js:108:419)
    at l$ (react-dom.production.min.js:160:170)
    at iZ (react-dom.production.min.js:278:18)
    at ia (react-dom.production.min.js:264:322)
    at react-dom.production.min.js:262:29
    at il (react-dom.production.min.js:262:29)
    at oJ (react-dom.production.min.js:255:92)
    at nb (react-dom.production.min.js:77:247)
    at nw (react-dom.production.min.js:78:403)
window.console.error @ app-index.tsx:25Understand this errorAI
pusher.js:3742 WebSocket connection to 'wss://localhost/websocket/app/keepappkey?protocol=7&client=js&version=8.3.0&flash=false' failed: 
createWebSocket @ pusher.js:3742Understand this errorAI
pusher.js:3742 WebSocket connection to 'ws://localhost/websocket/app/keepappkey?protocol=7&client=js&version=8.3.0&flash=false' failed: 
createWebSocket @ pusher.js:3742Understand this errorAI
pusher.js:3742 WebSocket connection to 'wss://localhost/websocket/app/keepappkey?protocol=7&client=js&version=8.3.0&flash=false' failed: 
createWebSocket @ pusher.js:3742Understand this errorAI
pusher.js:3742 WebSocket connection to 'ws://localhost/websocket/app/keepappkey?protocol=7&client=js&version=8.3.0&flash=false' failed: 
createWebSocket @ pusher.js:3742Understand this errorAI
pusher.js:3742 WebSocket connection to 'wss://localhost/websocket/app/keepappkey?protocol=7&client=js&version=8.3.0&flash=false' failed: 
createWebSocket @ pusher.js:3742Understand this errorAI
26Chrome is moving towards a new experience that allows users to choose to browse without third-party cookies.Understand this warningAI
pusher.js:3742 WebSocket connection to 'ws://localhost/websocket/app/keepappkey?protocol=7&client=js&version=8.3.0&flash=false' failed: 
createWebSocket @ pusher.js:3742
getSocket @ pusher.js:1662
connect @ pusher.js:1517
s @ pusher.js:3890
emit @ pusher.js:1475
changeState @ pusher.js:1625
transportConnectionInitializer @ pusher.js:3244
connect @ pusher.js:3919
tryStrategy @ pusher.js:2881
o @ pusher.js:2852
(anonymous) @ pusher.js:2878
(anonymous) @ pusher.js:918
(anonymous) @ pusher.js:891Understand this errorAI
pusher.js:3742 WebSocket connection to 'wss://localhost/websocket/app/keepappkey?protocol=7&client=js&version=8.3.0&flash=false' failed: 
createWebSocket @ pusher.js:3742
getSocket @ pusher.js:1662
connect @ pusher.js:1517
s @ pusher.js:3890
emit @ pusher.js:1475
changeState @ pusher.js:1625
transportConnectionInitializer @ pusher.js:3244
connect @ pusher.js:3919
tryStrategy @ pusher.js:2881
o @ pusher.js:2852
(anonymous) @ pusher.js:2878
(anonymous) @ pusher.js:918
(anonymous) @ pusher.js:891Understand this errorAI
pusher.js:3742 WebSocket connection to 'ws://localhost/websocket/app/keepappkey?protocol=7&client=js&version=8.3.0&flash=false' failed: 
createWebSocket @ pusher.js:3742
getSocket @ pusher.js:1662
connect @ pusher.js:1517
s @ pusher.js:3890
emit @ pusher.js:1475
changeState @ pusher.js:1625
transportConnectionInitializer @ pusher.js:3244
connect @ pusher.js:3919
tryStrategy @ pusher.js:2881
o @ pusher.js:2852
(anonymous) @ pusher.js:2878
(anonymous) @ pusher.js:918
(anonymous) @ pusher.js:891Understand this errorAI
pusher.js:3742 WebSocket connection to 'wss://localhost/websocket/app/keepappkey?protocol=7&client=js&version=8.3.0&flash=false' failed: 
createWebSocket @ pusher.js:3742
getSocket @ pusher.js:1662
connect @ pusher.js:1517
s @ pusher.js:3890
emit @ pusher.js:1475
changeState @ pusher.js:1625
transportConnectionInitializer @ pusher.js:3244
connect @ pusher.js:3919
tryStrategy @ pusher.js:2881
o @ pusher.js:2852
(anonymous) @ pusher.js:2878
(anonymous) @ pusher.js:918
(anonymous) @ pusher.js:891Understand this errorAI
pusher.js:3742 WebSocket connection to 'ws://localhost/websocket/app/keepappkey?protocol=7&client=js&version=8.3.0&flash=false' failed: 
createWebSocket @ pusher.js:3742
getSocket @ pusher.js:1662
connect @ pusher.js:1517
s @ pusher.js:3890
emit @ pusher.js:1475
changeState @ pusher.js:1625
transportConnectionInitializer @ pusher.js:3244
connect @ pusher.js:3919
tryStrategy @ pusher.js:2881
o @ pusher.js:2852
(anonymous) @ pusher.js:2878
(anonymous) @ pusher.js:918
(anonymous) @ pusher.js:891Understand this errorAI
pusher.js:3742 WebSocket connection to 'wss://localhost/websocket/app/keepappkey?protocol=7&client=js&version=8.3.0&flash=false' failed: 
createWebSocket @ pusher.js:3742
getSocket @ pusher.js:1662
connect @ pusher.js:1517
s @ pusher.js:3890
emit @ pusher.js:1475
changeState @ pusher.js:1625
transportConnectionInitializer @ pusher.js:3244
connect @ pusher.js:3919
tryStrategy @ pusher.js:2881
o @ pusher.js:2852
(anonymous) @ pusher.js:2878
(anonymous) @ pusher.js:918
(anonymous) @ pusher.js:891Understand this errorAI
pusher.js:3742 WebSocket connection to 'ws://localhost/websocket/app/keepappkey?protocol=7&client=js&version=8.3.0&flash=false' failed: 
createWebSocket @ pusher.js:3742
getSocket @ pusher.js:1662
connect @ pusher.js:1517
s @ pusher.js:3890
emit @ pusher.js:1475
changeState @ pusher.js:1625
transportConnectionInitializer @ pusher.js:3244
connect @ pusher.js:3919
tryStrategy @ pusher.js:2881
o @ pusher.js:2852
(anonymous) @ pusher.js:2878
(anonymous) @ pusher.js:918
(anonymous) @ pusher.js:891Understand this errorAI
pusher.js:3742 WebSocket connection to 'wss://localhost/websocket/app/keepappkey?protocol=7&client=js&version=8.3.0&flash=false' failed: 
createWebSocket @ pusher.js:3742
getSocket @ pusher.js:1662
connect @ pusher.js:1517
s @ pusher.js:3890
emit @ pusher.js:1475
changeState @ pusher.js:1625
transportConnectionInitializer @ pusher.js:3244
connect @ pusher.js:3919
tryStrategy @ pusher.js:2881
o @ pusher.js:2852
(anonymous) @ pusher.js:2878
(anonymous) @ pusher.js:918
(anonymous) @ pusher.js:891Understand this errorAI
```

**Comment by shahargl** [comment]
hey @nlamirault  - what `helm` and `keep` version you use?

can you try disable Pusher (add `PUSHER_DISABLED=true` on both frontend/backend) and tell me if you still have error?

**Comment by shahargl** [comment]
also - what do you say about join our Slack (https://slack.keephq.dev) so me and @talboren would be able to help faster?

**Comment by d4alpha** [comment]
I have the same problem. I am using the Helm Chart Version 0.1.45 and appVersion 0.30.7 
Beginning with appVersion 0.30.4 i see the mentioned error message. With version 0.30.3 the UI still works.

**Comment by shahargl** [comment]
hey @d4alpha - can you use `0.1.46` (with Keep `0.31.6`)? it should be solved.

**Comment by d4alpha** [comment]
I tried with 0.1.47 with appVersion 0.31.7 and i still get the following error:
Application error: a client-side exception has occurred (see the browser console for more information).

Console:
app-index.tsx:25 TypeError: y.map is not a function
    at A (AlertsLinks.tsx:122:55)
    at rE (react-dom.production.min.js:108:419)
    at l$ (react-dom.production.min.js:160:170)
    at iZ (react-dom.production.min.js:278:18)
    at ia (react-dom.production.min.js:264:322)
    at react-dom.production.min.js:262:29
    at il (react-dom.production.min.js:262:29)
    at oJ (react-dom.production.min.js:255:92)
    at nb (react-dom.production.min.js:77:247)
    at nw (react-dom.production.min.js:78:403)

**Comment by shahargl** [comment]
it's a different bug, can you please share a video of this crash? @d4alpha

**Comment by shahargl** [comment]
@d4alpha - if you DM me on our Slack I'll be able to solve it quickly

**Comment by nlamirault** [comment]
i add this into the backend and frontend:
```yaml
- name: PUSHER_DISABLED
   value: 'true'
```

and I've got the error.
Using Helm chart version `0.1.53` and Keep `v0.32.8`

**Comment by nlamirault** [comment]
works fine replacing `/v2` with `/backend`.
See https://github.com/keephq/helm-charts/commit/5ee90bad4f02cdbec9000336b2ebdf298b0e18da
